###############################################################################
# Created by write_sdc
###############################################################################
current_design apb_timer
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name PCLK -period 9.8 [get_ports {PCLK}]
set_clock_transition 0.1500 [get_clocks {PCLK}]
set_clock_uncertainty 0.2500 PCLK
set_propagated_clock [get_clocks {PCLK}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[0]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[10]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[11]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[1]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[2]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[3]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[4]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[5]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[6]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[7]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[8]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PADDR[9]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PENABLE}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PPROT[0]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PPROT[1]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PPROT[2]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRESETn}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PSEL}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PSTRB[0]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PSTRB[1]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PSTRB[2]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PSTRB[3]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[0]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[10]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[11]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[12]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[13]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[14]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[15]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[16]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[17]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[18]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[19]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[1]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[20]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[21]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[22]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[23]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[24]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[25]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[26]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[27]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[28]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[29]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[2]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[30]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[31]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[3]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[4]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[5]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[6]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[7]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[8]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWDATA[9]}]
set_input_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PWRITE}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[0]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[10]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[11]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[12]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[13]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[14]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[15]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[16]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[17]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[18]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[19]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[1]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[20]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[21]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[22]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[23]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[24]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[25]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[26]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[27]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[28]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[29]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[2]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[30]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[31]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[3]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[4]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[5]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[6]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[7]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[8]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PRDATA[9]}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PREADY}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {PSLVERR}]
set_output_delay 2.0000 -clock [get_clocks {PCLK}] -add_delay [get_ports {irq_o}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {PREADY}]
set_load -pin_load 0.0334 [get_ports {PSLVERR}]
set_load -pin_load 0.0334 [get_ports {irq_o}]
set_load -pin_load 0.0334 [get_ports {PRDATA[31]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[30]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[29]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[28]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[27]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[26]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[25]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[24]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[23]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[22]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[21]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[20]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[19]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[18]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[17]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[16]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[15]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[14]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[13]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[12]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[11]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[10]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[9]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[8]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[7]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[6]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[5]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[4]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[3]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[2]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[1]}]
set_load -pin_load 0.0334 [get_ports {PRDATA[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PCLK}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PENABLE}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PRESETn}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PSEL}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWRITE}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PADDR[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PPROT[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PPROT[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PPROT[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PSTRB[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PSTRB[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PSTRB[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PSTRB[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {PWDATA[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
