#!/usr/bin/env python3
"""Generate shared SystemVerilog, C++, and Markdown register definitions."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec" / "register_map.json"
SV_OUT = ROOT / "rtl" / "generated" / "apb_timer_regs.svh"
CPP_OUT = ROOT / "verification" / "cpp" / "include" / "generated" / "timer_registers.hpp"
MD_OUT = ROOT / "docs" / "generated" / "register-map.md"


def parse_int(value: str | int) -> int:
    return int(value, 0) if isinstance(value, str) else value


def main() -> None:
    data = json.loads(SPEC.read_text(encoding="utf-8"))
    regs = data["registers"]

    sv_lines = [
        "// Generated by scripts/generate_registers.py. Do not edit manually.",
        "`ifndef APB_TIMER_REGS_SVH",
        "`define APB_TIMER_REGS_SVH",
        "",
    ]
    cpp_lines = [
        "// Generated by scripts/generate_registers.py. Do not edit manually.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace timer_regs {",
    ]
    md_lines = [
        "# Generated Register Map",
        "",
        "> Generated from `spec/register_map.json`; do not edit manually.",
        "",
        "| Offset | Register | Access | Reset | Description |",
        "|---:|---|---|---:|---|",
    ]

    for reg in regs:
        name = reg["name"]
        offset = parse_int(reg["offset"])
        reset = parse_int(reg["reset"])
        sv_lines.append(f"localparam logic [11:0] APB_TIMER_{name}_ADDR = 12'h{offset:03X};")
        cpp_lines.append(f"inline constexpr std::uint32_t {name} = 0x{offset:03X}u;")
        cpp_lines.append(f"inline constexpr std::uint32_t {name}_RESET = 0x{reset:08X}u;")
        md_lines.append(
            f"| `0x{offset:03X}` | `{name}` | `{reg['access'].upper()}` | "
            f"`0x{reset:08X}` | {reg['description']} |"
        )
        for field in reg.get("fields", []):
            field_name = f"{name}_{field['name']}"
            lsb = int(field["lsb"])
            width = int(field["width"])
            if width == 32:
                mask = 0xFFFFFFFF
            else:
                mask = ((1 << width) - 1) << lsb
            sv_lines.append(f"localparam int unsigned APB_TIMER_{field_name}_LSB = {lsb};")
            sv_lines.append(f"localparam logic [31:0] APB_TIMER_{field_name}_MASK = 32'h{mask:08X};")
            cpp_lines.append(f"inline constexpr unsigned {field_name}_LSB = {lsb}u;")
            cpp_lines.append(f"inline constexpr std::uint32_t {field_name}_MASK = 0x{mask:08X}u;")
        sv_lines.append("")
        cpp_lines.append("")

    sv_lines.extend(["`endif", ""])
    cpp_lines.extend(["}  // namespace timer_regs", ""])

    SV_OUT.parent.mkdir(parents=True, exist_ok=True)
    CPP_OUT.parent.mkdir(parents=True, exist_ok=True)
    MD_OUT.parent.mkdir(parents=True, exist_ok=True)
    SV_OUT.write_text("\n".join(sv_lines), encoding="utf-8")
    CPP_OUT.write_text("\n".join(cpp_lines), encoding="utf-8")
    MD_OUT.write_text("\n".join(md_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
